---
name: Default
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt -- --check
      - run: cargo check --locked
      - run: cargo clippy --locked
      - run: cargo test --locked
      - run: cargo build --locked --release --verbose

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [main]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: docker
        with:
          images: |
            mfinelli/fbarcalc
            ghcr.io/mfinelli/fbarcalc
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker.outputs.tags }}
      - uses: peter-evans/dockerhub-description@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/fbarcalc
          short-description: ${{ github.event.repository.description }}
