---
name: Default
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt -- --check
      - run: cargo check --locked
      - run: cargo clippy --locked
      - run: cargo test --locked
      - run: cargo build --locked --release --verbose
      - run: ./vcheck.bash

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [main]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: docker
        with:
          images: |
            mfinelli/fbarcalc
            ghcr.io/mfinelli/fbarcalc
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker.outputs.tags }}
      - uses: peter-evans/dockerhub-description@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/fbarcalc
          short-description: ${{ github.event.repository.description }}

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [main, docker]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cargo vendor --locked
      - run: cargo doc --frozen --no-deps --release
      - run: cargo build --frozen --release
      - run: |
          cp target/release/fbarcalc .
          cp -r target/doc .
          rm -rfv doc/.lock
          tar acvf fbarcalc_${{ github.ref_name }}_amd64.tar.zst \
            Cargo.{lock,toml} CHANGELOG.md LICENSE README.md doc fbarcalc \
            src vendor
      - uses: ncipollo/release-action@v1
        with:
          artifacts: fbarcalc_*.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}
